# Generated by Django 2.2 on 2021-06-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_auto_20210628_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
